#!/usr/bin/perl

use lib 'lib';
use Mojo::Base -strict;
use OptArgs2 'class_optargs';
use App::podite::OptArgs;

my ( $class, $opts ) = class_optargs('App::podite');

eval "require $class" or die $@;
$class->new->run($opts);

__END__

=head1 NAME

podite - Command line podcast aggregator

=head1 SYNOPSIS

  podite

=head1 DESCRIPTION

podite downloads podcasts from a set of subscribed rss and atom feeds. You
can add feeds by url or search for them on gpodder.net. Feeds can be
deactivated if you are currently not interested in them without loosing
the information which episode you already downloaded. Episodes can be
hidden, so they will not clutter your screen (unless you want to!).

=head1 INSTALLATION

The easiest way to install podite is with
L<cpanminus|https://github.com/miyagawa/cpanminus>:

  cpanm git://github.com/mdom/podite.git

=head1 EXAMPLES

  $ podite --help

  $ podite add http://feeds.twit.tv/floss.xml https://gastropod.com/feed/

  $ podite feeds
  1 http://feeds.twit.tv/floss.xml   FLOSS Weekly (MP3)
  2 https://gastropod.com/feed/      Gastropod

  $ podite update

  $ podite episodes
  [...]

  $ podite download 1 4-6 20-

=head1 COMMANDS

=item add URL...

This action will prompt you for an url of an RSS feed and download it.

=item delete URL...

Deletes one of your feeds. By deleteting a feed you'll loose any
data for it, for example the list of downloaded, skipped or ignored
feed entries. If you just want to temporarily disable a feed use
I<disable>.

=item move OLD_URL NEW_URL

Changes the url of a feed.

=item disable URL

Disable feed. All state is preserved.

=item enable URL

Enables a formerly disables feed.

=item status

Displays a list of currently subscribed and active podcasts. For every
podcast the number of new, skipped and total episodes are listed. A
episode is counted as skipped if you have already seen it in the download
dialog but haven't downloaded or hidden it.

=item update

Updates all feeds and show their status.

=item download EPISODES

Downloads episodes.

=back

=head1 COPYRIGHT AND LICENSE

Copyright 2018 Mario Domgoergen E<lt>mario@domgoergen.comE<gt>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

=head1 AUTHOR

Mario Domgoergen E<lt>mario@domgoergen.comE<gt>

=cut

